src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>MyExtID__c</fullName>
        <externalId>true</externalId>
        <label>MyExtID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>MyExtID__c</fullName>
        <externalId>true</externalId>
        <label>MyExtID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Mileage__c.object
<CustomObject>
    <description>An object that holds mileage information for a trip.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person that was seen on this  trip.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Mileage</relationshipLabel>
        <relationshipName>Mileage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Date of Mileage report</description>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Miles__c</fullName>
        <description>Miles driven</description>
        <label>Miles</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Mileage</label>
    <nameField>
        <displayFormat>MR-{0000}</displayFormat>
        <label>Mileage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mileage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ParentChildSampleMileageContact.cls
public class ParentChildSampleMileageContact {
    public static void InsertParentChild() {
        Date dt = Date.today();
                Mileage__c  newmileage = new Mileage__c(
                        Miles__c=50,
                         Date__c=dt);
        
        // Create the parent reference.        // Used only for foreign key reference        // and doesn't contain any other fields.
        contact conctReference = new contact(
           LastName='Jones',
            MyExtID__c='SAP111111');                
        newmileage.Contact__r= conctReference;
        
        // Create the Account object to insert.        // Same as above but has Name field.        // Used for the insert.
        contact parentContact = new contact(
             FirstName='Harry', LastName='Jones',
            MyExtID__c='SAP111111');      
        
        // Create the account and the opportunity.
        Database.SaveResult[] results = Database.insert(new SObject[] {
             parentContact,newmileage});
        
        
        // Check results.        
        for (Integer i = 0; i < results.size(); i++) {
            if (results[i].isSuccess()) {
            System.debug('Successfully created ID: '
                  + results[i].getId());
            } else {
            System.debug('Error: could not create sobject '
                  + 'for array element ' + i + '.');
            System.debug('   The error reported was: '
                  + results[i].getErrors()[0].getMessage() + '\n');
            }
        }
    }
    
}