src/objects/Resources__c.object
<CustomObject>
    <fields>
        <fullName>Current_Status__c</fullName>
        <label>Current Status</label>
        <picklist>
            <picklistValues>
                <fullName>Free</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Allocated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reserved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OverAll_Experience__c</fullName>
        <label>OverAll Experience</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Resource_Name__c</fullName>
        <label>Resource Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Resources</label>
    <nameField>
        <displayFormat>RNum-{0000}</displayFormat>
        <label>Resource Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/reportcontroller.cls
public with sharing class reportcontroller {
public List<Resources__c> listrec{get;set;}
public string pval{get;set;}
public Resources__c rept{get;set;}
public reportcontroller(ApexPages.standardController controller) {
      this.rept= (Resources__c)controller.getRecord();
    }

public PageReference displayrec() {
        listrec = [SELECT Resources__c.Resource_Name__c,Resources__c.OverAll_Experience__c 
                   FROM Resources__c WHERE Current_Status__c= : rept.Current_Status__c];
        System.debug('+++++ : ' + listrec + ' : ' + rept.Current_Status__c);
       //return listrec ;
       return null; 
    }
  public String getChooserender() {
     if (ApexPages.currentPage().getParameters().get('p') != null)
        return 'pdf';
        else
      return null;
  }
public PageReference deliverAsPDF() {
      PageReference pdf =  Page.demoreports;
        pdf.getParameters().put('p','p');
        
        return pdf;
  }
  
}